name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configurar Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker
        run: |
          # Usando o SHA do commit para garantir que o Smoke Test valide a versão exata
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/labsnet-repo/labsnet-api:${{ github.sha }} .

      # --- CAMADA DE SEGURANÇA: TRIVY ---
      - name: Scan de Vulnerabilidades (Trivy)
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: 'us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/labsnet-repo/labsnet-api:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/labsnet-repo/labsnet-api:${{ github.sha }}

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy labsnet-api \
            --image us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/labsnet-repo/labsnet-api:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      # --- CAMADA DE CONFIANÇA: SMOKE TEST ---
      - name: Smoke Test (Health Check)
        run: |
          # 1. Busca a URL que o Google atribuiu ao serviço
          APP_URL=$(gcloud run services describe labsnet-api --platform managed --region us-central1 --format 'value(status.url)')
          
          echo "Iniciando Smoke Test na rota: $APP_URL/health"
          
          # 2. Faz a chamada ao seu endpoint FastAPI
          # Adicionei um filtro grep para validar se o "status: ok" está no corpo da resposta
          RESPONSE=$(curl -s "$APP_URL/health")
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL/health")
          
          echo "Resposta do App: $RESPONSE"
          
          if [ "$STATUS" -eq 200 ] && [[ "$RESPONSE" == *"ok"* ]]; then
            echo "✅ Aplicação está online e retornando 'ok'!"
          else
            echo "❌ Falha crítica: Status HTTP $STATUS ou resposta inesperada."
            exit 1
          fi
