name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Auth GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configurar Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/labsnet-repo/labsnet-api .

      - name: Push Docker
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/labsnet-repo/labsnet-api

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy labsnet-api \
            --image us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/labsnet-repo/labsnet-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
