name: CI Pipeline

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          pytest

      - name: Lint (qualidade de código)
        run: |
          flake8 .

      - name: Security check
        run: |
          safety check
