name: CI Pipeline

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip' # Acelera a pipeline nas próximas execuções

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          # Define o path para que o pytest enxergue a pasta app
          export PYTHONPATH=$PYTHONPATH:.
          pytest

      - name: Lint (qualidade de código)
        run: |
          # Mantendo seus ignores e adicionando estatísticas para facilitar a correção depois
          flake8 app tests --ignore=E302,E305,W391,W292 --count --statistics

      - name: Security check (Dependencies)
        run: |
          pip install pip-audit
          # O parâmetro -r aponta para o seu arquivo de dependências
          pip-audit -r requirements.txt
